### ISSUE TITLE
TreeMultiMesh leaf matierial alpha is black instead of transparent

### ISSUE THREAD

**Issue by golddotasksquestions** [Arnklit/WaterGenGodotDemo#1] opened 2020-12-19 14:55 UTC
Win, 64, Dedicated Nvidea
Both in the Editor (Godot 3.2.3 stable) as well as when the project runs.

![tree_alpha](https://user-images.githubusercontent.com/47016402/102692281-a335f900-4212-11eb-9bd2-fb4b53e4ea4b.png)

**Comment by Arnklit** [comment] 2020-12-20 10:49
I cannot reproduce this, When I open up a fresh download of the demo everything is correct.

I'm wondering if it has something to do with how I'm discarding transparent pixels in my shader.

Would you mind checking if you see the same error when opening my fur demo? It uses the same method for the alpha clipping?

https://github.com/Arnklit/ShellFurGodotDemo

**Comment by golddotasksquestions** [comment] 2020-12-20 11:54
I can't find any of the same black alpha textures in the ShellFurGodotDemo.

**Comment by Arnklit** [comment] 2020-12-28 05:50
I believe I isolated the issue. Someone else had the issue on their machine and after trying a few things it turned out that the way I was discarding pixels to fix the alpha scissoring issue Godot has, caused this on some machines.

The fix has been pushed to the repository.

You can also manually apply the fix by selecting the tree branch material and clicking on the shader and replacing this:

```
if (alpha_scissor_threshold > albedo.a * albedo_tex.a) {
  discard;
}
```

with this:

```ALPHA = float(alpha_scissor_threshold < albedo.a * albedo_tex.a);```

**Comment by golddotasksquestions** [comment] 2020-12-29 21:54
I downloaded the demo again to test the fix.
The black alpha on the leafs is gone, but there is constant black flicking now in the editor as well as when the game runs:

Editor:
https://user-images.githubusercontent.com/47016402/103316094-b40f1780-4a27-11eb-9518-9ab5d56f16c0.mp4

Game running:
https://user-images.githubusercontent.com/47016402/103316134-cee18c00-4a27-11eb-94c8-b3f1dd780d20.mp4

The first time I ran the demo, the game was fine for a split second, then halve the map was pure black. This effect was stable, not flickering and only while running the game. I could move around like normally, the black did not flicker and neither did the areas unaffected by the black. Here is me zooming out to give you a view about what areas where affected:
![river_stable_black](https://user-images.githubusercontent.com/47016402/103316317-69da6600-4a28-11eb-85ca-2dbada11d101.png)
Do you think this is reflection probe related?

The refraction on the other hand really looks fantastic now, love it! :
https://user-images.githubusercontent.com/47016402/103316405-ba51c380-4a28-11eb-9b6b-44e6716602d4.mp4

**Comment by Arnklit** [comment] 2020-12-30 06:59
Yeah I'm seeing these issues from time to time as well, unfortunately they have not been very consistent. Some of them are definitely related to reflection probes as it is exactly the area of the reflection probes that turn black. I'll investigate further.

**Comment by Arnklit** [comment] 2021-01-10 12:44
Would you mind testing this again in the 0.2.0 version of the demo, I think most of this should be ironed out now.

**Comment by golddotasksquestions** [comment] 2021-01-15 07:54
Tested v0.2.0, first time I ran it, it looked great! Had fun toying around with the rubber ducks even though the framerate tanks on my 7 year old hardware (dedicated Nvidea)
Then I closed the running game, moved around in the 3D editor for a bit (without changing anything), ran the game again, and within a few seconds:
![image](https://user-images.githubusercontent.com/47016402/104696721-00887180-570f-11eb-8187-67bf909a062c.png)

This black area is not flickering, it's stable. Also when moving around. Made the screenshot, exited the game and tried to replicate by moving around the editor, running the game again a few times, but I could not replicate it any more.

**Comment by Arnklit** [comment] 2021-01-15 08:50
Yeah it's the reflection probes causing it, the black area is the area they cover and if you disable them, it goes away. I think this is some general Godot issue, but it's not happening consistently enough for me that I can get a bug logged on it.

I think I will remove the reflection probes for the next release, I'm not sure that add all that much to the scene anyway.

**Comment by Arnklit** [comment] 2021-01-27 13:44
I have removed the reflection probes now in the 0.2.1 release as they kept being buggy and didn't really add much. Do you see any more issues with this new release?

**Comment by golddotasksquestions** [comment] 2021-01-28 11:21
Seems stable in my system. No black rendering issues anymore. The lava stream is really cool, btw!

**Comment by Arnklit** [comment] 2021-01-28 12:21
Awesome and thanks. Closing :).

**Closed as completed by Arnklit** 2021-01-28 12:21 UTC
Labels: bug
